baseURL = "https://docs.r-hub.io/"
languageCode = "en-us"

title = "R-hub Docs site (WIP!)"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
externalTitle = "R-hub Docs site"
sidebarColor = "default"
customCss = []

[[menu.shortcuts]]
name = "R-hub"
url = "https://builder.r-hub.io/"
weight = 10

[[menu.shortcuts]]
name = "Github"
url = "https://github.com/r-hub"
weight = 20
