baseURL = "https://docs.r-hub.io/"
languageCode = "en-us"

title = "R-hub Docs"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
externalTitle = "R-hub Docs"
description = "Documentation website for the R-hub project of the R Consortium, easing the R package development process."
sidebarColor = "default"
customCss = []

[[menu.shortcuts]]
name = "R-hub"
url = "https://builder.r-hub.io/"
weight = 10

[[menu.shortcuts]]
name = "GitHub"
url = "https://github.com/r-hub"
weight = 20
